ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER app_admin IDENTIFIED BY 123456;

-- Quyền cơ bản
GRANT DBA TO app_admin;
GRANT SELECT ANY DICTIONARY TO app_admin;
GRANT SELECT ANY TABLE TO app_admin;

-- Quản lý User
GRANT CREATE USER TO app_admin WITH ADMIN OPTION;
GRANT DROP USER TO app_admin WITH ADMIN OPTION;
GRANT ALTER USER TO app_admin WITH ADMIN OPTION;

-- Quản lý Role
GRANT CREATE ROLE TO app_admin WITH ADMIN OPTION;

-- Phân quyền
GRANT GRANT ANY PRIVILEGE TO app_admin WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO app_admin WITH ADMIN OPTION;
GRANT GRANT ANY OBJECT PRIVILEGE TO app_admin WITH ADMIN OPTION;

-- Tạo View nội bộ 
GRANT CREATE VIEW TO app_admin;

-- Lệnh mở rộng cho việc Xoá/Chỉnh sửa Role
GRANT DROP ANY ROLE TO app_admin;
GRANT ALTER ANY ROLE TO app_admin;

-- Cấp trực tiếp quyền truy vấn danh mục Hệ thống để tránh lỗi ORA-41904 lúc tạo View hiển thị
GRANT SELECT ON SYS.DBA_USERS TO app_admin;
GRANT SELECT ON SYS.DBA_ROLES TO app_admin;
GRANT SELECT ON SYS.DBA_SYS_PRIVS TO app_admin;
GRANT SELECT ON SYS.DBA_TAB_PRIVS TO app_admin;
GRANT SELECT ON SYS.DBA_COL_PRIVS TO app_admin;
GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO app_admin;
GRANT SELECT ON SYS.ROLE_TAB_PRIVS TO app_admin;

-- Điều khiển phiên
GRANT ALTER SESSION TO app_admin WITH ADMIN OPTION;

SHOW CON_NAME;
